### ISSUE TITLE
net45 actually targets 452

### ISSUE THREAD

**Issue by DGuidi** [schneidenbach/AutoMapper.Attributes#12]
using nuget package with plain framework 4.5 doesn't work, looks dll dargets 452 anyway.
this is true for 5.0.1 (single dll targets 4.5) but also for previous 5.0.0 (both dll targets 4.5.2)

**Comment by schneidenbach** [comment]
Thanks for pointing this out - I'm switching the target to 4.5 in the next release (happening shortly)

**Comment by schneidenbach** [comment]
Now targets 4.5 and .NET Standard 1.3!
