### ISSUE TITLE
error using with automapper != 5.0.2

### ISSUE THREAD

**Issue by DGuidi** [schneidenbach/AutoMapper.Attributes#13]
I'm using a newer (5.2.0) version of Automapper.dll, but looks 5.0.2 version is required.

**Comment by DGuidi** [comment]
I've take a look at the code in master and looks specificversion is set to true for automapper dll.

P.S: I can suggest you to tag releases in repository?

**Comment by schneidenbach** [comment]
good call on both - I'll tag the next release plus turn SpecificVersion off.

**Comment by schneidenbach** [comment]
AutoMapper.Attributes 6.0 released - now supports any version 5.0.2 and up!
