### ISSUE TITLE
Library breaks under AutoMapper 5.x

### ISSUE THREAD

**Issue by schneidenbach** [schneidenbach/AutoMapper.Attributes#2]
MapTypes() extension method doesn't work at all when using v.5 of AutoMapper.

**Comment by igolets** [comment]
[InvalidOperationException: Sequence contains no matching element]
   System.Linq.Enumerable.Single(IEnumerable`1 source, Func`2 predicate) +2691669
   AutoMapper.Attributes.Extensions..cctor() +138

**Comment by schneidenbach** [comment]
@igolets I have the problem mostly addressed - just one minor issue outstanding.  Stay tuned!

**Comment by MrZander** [comment]
@schneidenbach Curious for an ETA for this or if you need any help?

**Comment by schneidenbach** [comment]
The latest version of AutoMapper.Attributes is here at this branch: https://github.com/schneidenbach/AutoMapper.Attributes/tree/pr/1

I could use some help actually.  I have a couple of open issues - one related to a broken unit test, another related to modifying my NuSpec file to point each separate AutoMapper.Attributes

The broken unit test isn't blocking a deploy to NuGet - that's a bit of an edge use case for AutoMapper that can be fixed in a future version.  I'm currently researching NuSpec to see what I need to do to assign one DLL to a specific version of AutoMapper.  https://github.com/schneidenbach/AutoMapper.Attributes/issues/4

**Comment by mlhDevelopment** [comment]
Any updated ETA?

**Comment by schneidenbach** [comment]
The latest version of AutoMapper.Attributes is available on NuGet.  It supports AutoMapper 5.x and up.  If you still need support for 4.x, use package version 1.0.20.
