### ISSUE TITLE
Add support for MapFromProperty Lambda expressions

### ISSUE THREAD

**Issue by Bitmapped** [schneidenbach/AutoMapper.Attributes#21]
It'd be great if AutoMapper.Attributes supported mapping using Lambda expressions like regular AutoMapper does. Mapping using Attributes appears to break down when I get into mapping values from structs attached to properties, whereas the regular AutoMapper works fine with this when using Lambda expressions.

**Comment by schneidenbach** [comment]
Can you send me a project where structs attached to properties isn't working for you?  Lambda expressions can't be added to attributes directly, but you can get the same behavior by subclassing MapsFrom/MapsToAttribute like so: https://github.com/schneidenbach/AutoMapper.Attributes#ok-but-i-need-some-super-custom-mapping-behavior

**Comment by Bitmapped** [comment]
Thanks for letting me know that Lambda expressions aren't possible directly.

I'm looking back at the Struct mapping issue. I must have done something wrong earlier because when I code up things now, they seem to be mapping OK.

I'm going to close out this ticket since it doesn't seem to serve a purpose at this point.
