### ISSUE TITLE
Alter NuSpec to install different version of AutoMapper.Attributes based on the current version of AutoMapper

### ISSUE THREAD

**Issue by schneidenbach** [schneidenbach/AutoMapper.Attributes#4]
AutoMapper v.4.2.1 to v4.x should use the V4 DLL
AutoMapper v.5.x - ? should use the V5 DLL

**Comment by MrZander** [comment]
To my knowledge, there is no way to install a different version of the package based on what dependency is _already_ installed. 

In my (limited knowledge) opinion, the best approach is to raise the minimum required version of AutoMapper to 5.0.  
Anyone who wished to use an older version of AutoMapper can install an older version of AutoMapper.Attributes.

**Comment by schneidenbach** [comment]
I think that moving to requiring AutoMapper 5.0 is the best solution, but I want to make sure that the use case covered by my failing unit test is in line with the expected behavior of AutoMapper 5.0.  Still in progress...

**Comment by schneidenbach** [comment]
Updated library to 5.0.
