### ISSUE TITLE
ReverseMap

### ISSUE THREAD

**Issue by hcd** [schneidenbach/AutoMapper.Attributes#6]
Hi,

Fantastic package :) One issue though, the ReverseMap doesn't work as explained in the documentation.
It states : 
"You can set the ReverseMap property in the [MapsTo]/[MapsFrom] attribute to true if you want to map the classes in reverse as well, like this:
[MapsTo(typeof(Customer), true)]    //this will map Customer to Person and Person to Customer"

But since ReverseMap is not an argument of the MapsToAttribute constructor, this doesn't work. Can be circumenvented by setting it via a named parameter, ie.:
[MapsTo(typeof(Customer), ReverseMap = true)]  

Maybe add an optional parameter to the constructor ?

Kind regards,
Sven.

**Comment by schneidenbach** [comment]
Good catch.  I went ahead and updated the documentation.

I like the named parameter approach as it's a bit more self-documenting.  I thought about adding in an attribute that allows two-way mapping without specifying ReverseMap.  Thoughts on that for both types and properties?

**Comment by hcd** [comment]
Hi,

yes, a new attribute MapsTwoWayTo or MapsBidirectionallyTo so would also be nice :)

**Comment by schneidenbach** [comment]
Added MapsToAndFromProperty for two-way property mapping!
